services:
  - type: web
    name: bookflow-ai-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://bookflow-ai-backend.onrender.com
